version: '3'

services:
  #Контейнер с php-fpm
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    env_file:
      - .env
    volumes:
      - ./:/data/mysite.local
    working_dir: /data/mysite.local
    networks:
      - app-network

  #контейне с Nginx
  webserver:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/data/mysite.local
    networks:
      - app-network

  # контейнер с MySQL
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge